server:
  port: 8015
dubbo:
  application:
    name: springboot-dubbo-mongo-StaffManagement-consumer
  registry:
    address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183
  metadata-report:
    address: zookeeper://127.0.0.1:2183